#!/bin/sh
hex2mac() {
	MAC=""
	seq 2 2 12 | while read i
	do
		echo -n ${1} | head -c $i | tail -c 2
		if [ $i != 12 ]
		then
			echo -n ':'
		fi
	done | tr '[:upper:]' '[:lower:]'
}

if [ "${1}" = start ]
then
	prefix=licheervnano
	if [ -e /boot/hostname.prefix ]
	then
		prefix=$(cat /boot/hostname.prefix)
	fi
	old_hostname=$(cat /etc/hostname)
	new_hostname=${prefix}-$(sha512sum /device_key_legacy | head -c 4)
	if [ -e /proc/ax_proc/uid ]
	then
		new_hostname=${prefix}-$(sha512sum /device_key | head -c 4)
	fi

	if [ -e /boot/hostname ]
	then
		new_hostname=$(cat /boot/hostname)
	fi

	if [ "${old_hostname}" != "${new_hostname}" ]
	then
		hostname ${new_hostname}
		echo ${new_hostname} > /etc/hostname
		sed -i -e "s/${old_hostname}/${new_hostname}/g" /etc/hosts
	fi
	if ! grep -q ${new_hostname} /etc/hosts
	then
		sed -i -e "s/licheervnano $/${new_hostname}/g" /etc/hosts
		sed -i -e "s/licheervnano$/${new_hostname}/g" /etc/hosts
	fi
	echo "hostname: ${new_hostname}"

	# The WiFi interface advertises its own DHCP/DNS name (<hostname>-wifi) so
	# the router does not conflate it with the ethernet name. The per-device
	# suffix is only known here, so an image built with just a hostname
	# *prefix* cannot have this stanza baked in at build time.
	if [ -f /etc/dhcpcd.conf ] && ! grep -qE '^[[:space:]]*interface[[:space:]]+wlan0' /etc/dhcpcd.conf
	then
		printf '\ninterface wlan0\n\thostname %s-wifi\n' "${new_hostname}" >> /etc/dhcpcd.conf
		echo "wifi dhcp hostname: ${new_hostname}-wifi"
	fi

	if [ -e /boot/eth.mac ]
	then
		new_ethmac=$(cat /boot/eth.mac)
	elif [ -e /proc/ax_proc/uid ]
	then
		new_ethmac=$(hex2mac 48da356d$(sha512sum /device_key | head -c 4))
	else
		new_ethmac=$(hex2mac 48da356f$(sha512sum /device_key_legacy  | head -c 4))
	fi

	#ifconfig eth0 down
	ip link set eth0 address ${new_ethmac}
	#ifconfig eth0 up
	#ifconfig end0 down
	ip link set end0 address ${new_ethmac}
	#ifconfig end0 up
	echo "ethernet mac address: ${new_ethmac}"
fi
